# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

# Anchors
# https://circleci.com/docs/introduction-to-yaml-configurations#anchors-and-aliases
job-config: &job-config
  docker:
      - image: cimg/node:16.15.0

# Creating reusable commands
# https://circleci.com/docs/reusing-config#authoring-reusable-commands
commands:
  npm-install:
    steps:
      - checkout
      - node/install-packages
  npm-build:
    steps:
      - run:
          command: npm run build
          name: Build
  npm-test:
    steps:
      - run:
          command: npm run test
          name: Test
  persist-project:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  persist-release:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - CHANGELOG.md
            - package.json
            - package-lock.json
  persist-build:
    steps:
      - persist_to_workspace:
          root: .
          paths: 
            - build
  attach-to-project:
    steps:
      - attach_workspace:
          at: .

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install:
    <<: *job-config
    steps:
      - npm-install
      - persist-project
  test:
    <<: *job-config
    steps:
      - attach-to-project
      - npm-test
  release:
    <<: *job-config
    steps:
      - attach-to-project
      - run: npm run semantic-release
      - persist-release
  build:
    <<: *job-config
    steps:
      - attach-to-project
      - npm-build
      - persist-build
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach-to-project
      - aws-cli/install
      - run:
          name: Sync S3 Bucket
          command: aws s3 sync build/ s3://$BUCKET_NAME --delete
      # Useless for now
      # - run:
      #     name: Invalidate CloudFront Distribuition
      #     command: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy:
    # Creating conditions
    # https://circleci.com/docs/configuration-reference#logic-statements
    # https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows
    when:
      or:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [develop, << pipeline.git.branch >>]
        # - equal: [circleci-project-setup, << pipeline.git.branch >>]
    jobs:
      - to-approve:
          type: approval
      - install:
          requires: [to-approve]
      - build:
          requires: [install]
      - test:
          requires: [install]
      - deploy:
          requires: [build, test]
      
  new-release:
    # Creating conditions
    # https://circleci.com/docs/configuration-reference#logic-statements
    # https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows
    when:
      # equal: [staging, << pipeline.git.branch >>]
      equal: [circleci-project-setup, << pipeline.git.branch >>]
    jobs:
      - to-approve:
          type: approval
      - install:
          requires: [to-approve]
      - test:
          requires: [install]
      - release:
          context: github-auth
          requires: [test]
      - build:
          requires: [release, test]
      # It worked. No need to explore it further
      # - deploy:
      #     context: org-global
      #     requires: [build]